apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: krapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-puma
  template:
    metadata:
      name: krapp
      labels:
        app: rails-puma
    spec:
      containers:
        - name: krapp
          image: atul9/krapp:welcome
          imagePullPolicy: Always
          ports:
            - containerPort: 3000